# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoMembershipUpshell' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoMembershipUpshell
  pod 'Thumbprint'

  target 'DemoMembershipUpshellTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoMembershipUpshellUITests' do
    # Pods for testing
  end

end
